### ISSUE TITLE
Unexpected "?" Message.php line 73

### ISSUE THREAD

**Issue by deivisjl** [HepplerDotNet/flash-toastr#1]
I'm working with Laravel 5.4 and php 5.6.4, I got the plugin but when I ran it I threw the error: Unexpected "?" Message.php line 73 (It is for the ternary operator, perhaps by the php version)
I made it work like this:

```
public function offsetGet($offset)
    {
        if($this->$offset)
        {
            return $this->$offset;
        }
        else
        {
            return null;
        }
    }
```

**Comment by HepplerDotNet** [comment]
I just released 5.6.1 wich will fix this.
